include: package:pedantic/analysis_options.yaml

analyzer:
  exclude:
    - build/**
    - "**/*.g.dart"
  strong-mode:
    implicit-casts: false
  errors:
    missing_required_param: error
    parameter_assignments: error
    avoid_relative_lib_imports: error
linter:
  rules:
    - always_declare_return_types
    - camel_case_types
    - empty_constructor_bodies
    - annotate_overrides
    - avoid_init_to_null
    - constant_identifier_names
    - one_member_abstracts
    - slash_for_doc_comments
    - sort_constructors_first
    - unnecessary_brace_in_string_interps
